services:
  php:
    build:
      context: ./docker/php
    container_name: xplendor-php
    restart: unless-stopped
    volumes:
      - ./server:/var/www
      - /var/www/vendor
      - ./docker/php/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    working_dir: /var/www
    depends_on:
      - mysql
    networks:
      - xplendor

  mysql:
    image: mysql:8.0
    container_name: xplendor-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xplendor
      MYSQL_USER: xplendor
      MYSQL_PASSWORD: xplendor
    ports:
      - "3306:3306"
    volumes:
      - xplendor_mysql:/var/lib/mysql
    networks:
      - xplendor

  nginx:
    image: nginx:latest
    container_name: xplendor-nginx
    ports:
      - "8000:80"
    volumes:
      - ./server:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - xplendor

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: xplendor-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - xplendor

  next:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: xplendor-next
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - xplendor

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: xplendor-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Lisbon
      - TZ=Europe/Lisbon
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - xplendor

networks:
  xplendor:


volumes:
  xplendor_mysql:
  n8n_data:
